name: Sync Munki Repo

on:
  push:
    paths:
    - 'munki_repo/**'
    branches:
    - master
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
        with:
          lfs: 'true'
          fetch-depth: 1

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
          sudo installer -pkg ./AWSCLIV2.pkg -target /
          sudo rm AWSCLIV2.pkg
      
      - name: Install Munki
        run: |
          curl -OL https://github.com/munki/munki/releases/download/v5.6.3/munkitools-5.6.3.4401.pkg
          sudo installer -pkg munkitools-5.6.3.4401.pkg -target /
          sudo rm munkitools-5.6.3.4401.pkg
    
      - name: Run makecatalogs
        run : |
          /usr/local/munki/makecatalogs "$GITHUB_WORKSPACE"/munki_repo
      - name: Run AWS s3 sync
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run : |
          aws s3 sync "$GITHUB_WORKSPACE"/munki_repo s3://<ADD-YOUR-BUCKET-ID-HERE> --exclude '.DS_Store' --exclude '.keep' --delete
  
  slack-notify:
    runs-on: ubuntu-latest
    needs: sync-repo
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 #v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/8826633?s=200&v=4
          SLACK_USERNAME: Github Actions
          SLACK_FOOTER: 
          MSG_MINIMAL: true
          SLACK_TITLE: Munki repo was synced
